# Generated by Django 5.0.6 on 2024-07-10 06:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest_price', models.IntegerField(default=0, verbose_name='suggest price')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auction',
            },
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_library/')),
            ],
            options={
                'verbose_name': 'MediaLibrary',
                'verbose_name_plural': 'MediaLibraries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('location', models.URLField(verbose_name='location')),
                ('desc', models.TextField(verbose_name='description')),
                ('characteristic', ckeditor.fields.RichTextField(verbose_name='characteristic')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order'],
            },
        ),
    ]
