# Generated by Django 5.0.6 on 2024-07-10 06:00

import common.utils
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=120, validators=[common.utils.validate_phone_number], verbose_name='phone number')),
                ('full_name', models.CharField(max_length=120, verbose_name='full name')),
                ('last_name', models.CharField(max_length=120, verbose_name='last_name')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('address', models.CharField(max_length=120, verbose_name='address')),
                ('payment_method', models.CharField(choices=[('by card', 'by card'), ('cash', 'cash')], default='cash', max_length=120, verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='report')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Report',
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('desc', models.TextField(verbose_name='description')),
                ('image', models.ManyToManyField(to='common.media', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoriesCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=120, verbose_name='material')),
                ('desc', models.TextField(verbose_name='description')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.accessories', verbose_name='accessory')),
            ],
            options={
                'verbose_name': 'Accessories Characteristics',
                'verbose_name_plural': 'Accessories Characteristics',
            },
        ),
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.brandcategory')),
            ],
            options={
                'verbose_name': 'Brand Category',
                'verbose_name_plural': 'Brand Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('is_home_page', models.BooleanField(default=False, verbose_name='is_home_page')),
                ('desc', models.TextField(verbose_name='description')),
                ('color', models.CharField(choices=[('W', 'White'), ('CH', 'Black'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='W', max_length=120, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shop.brandcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory', to='shop.product', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.CharField(max_length=120, verbose_name='diagonal')),
                ('operational_memory', models.CharField(max_length=120, verbose_name='operational_memory')),
                ('SIM_quantity', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three')], default='1', max_length=120, verbose_name='quantity sim')),
                ('chip', models.CharField(max_length=120, verbose_name='chip')),
                ('built_in_memory', models.CharField(max_length=120, verbose_name='built_in_memory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Characteristic',
                'verbose_name_plural': 'Product Characteristics',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='common.media', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
    ]
