# Generated by Django 5.0.6 on 2024-07-10 06:00

import ckeditor.fields
import common.utils
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, verbose_name='address')),
                ('work_schedule', models.CharField(max_length=120, verbose_name='work schedule')),
                ('phone_number', models.CharField(max_length=120, verbose_name='phone number')),
                ('underground_station', models.CharField(max_length=120, verbose_name='underground station')),
                ('location', models.URLField(verbose_name='location')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='DescribeFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('device_type', models.CharField(max_length=120, verbose_name='device_type')),
                ('phone_number', models.CharField(max_length=120, validators=[common.utils.validate_phone_number], verbose_name='phone number')),
                ('brand_and_model', models.CharField(max_length=120, verbose_name='model')),
                ('desc', models.TextField(verbose_name='description')),
                ('agree_or_disagree', models.BooleanField(default=False, verbose_name='agree or disagree')),
            ],
            options={
                'verbose_name': 'Describe fault',
                'verbose_name_plural': 'Describe faults',
            },
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('advantages', models.CharField(max_length=120, verbose_name='advantages')),
                ('desc', models.TextField(verbose_name='description')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
            ],
            options={
                'verbose_name': 'About Service',
                'verbose_name_plural': 'About Services',
            },
        ),
        migrations.CreateModel(
            name='Faults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Fault',
                'verbose_name_plural': 'Faults',
            },
        ),
        migrations.CreateModel(
            name='TypesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('problems', ckeditor.fields.RichTextField(verbose_name='problems')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Types of work',
                'verbose_name_plural': 'Types of works',
            },
        ),
        migrations.CreateModel(
            name='WhatWeRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
            ],
            options={
                'verbose_name': 'What we repair',
                'verbose_name_plural': 'What we repair',
            },
        ),
        migrations.CreateModel(
            name='WhatWeRepairCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media', verbose_name='image')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='service.whatwerepaircategory')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('problems', ckeditor.fields.RichTextField(verbose_name='problems')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='service.whatwerepaircategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
